### ISSUE TITLE
please use line breaks in supplied source files

### ISSUE THREAD

**Issue by bcullman** [SAP/theming-base-content#1]
Many of the supplied source files have line breaks removed, making them impossible to parse. See:

* https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3/css_variables.css
* https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3/sass_variables.scss
* https://github.com/SAP/theming-base-content/blob/master/content/Base/baseLib/sap_fiori_3/preview-RTL.css

Can you provide them as readable files and let the consumer tooling (webpack etc) handle minification, or perhaps provide both compressed and uncompressed variations?

**Comment by andreas-roessler** [comment]
The files are not human-readable but still parse-able as they work in the browsers.

The variable-files should be presented in a way that they can be read by humans to get a better overview of the existing variables. We need to think about that. Maybe we just switch off the “compression”.

If you want to parse the files you cannot rely on the whitespace structure. This will change eventually. A simple string separation by e.g. RegExp is not sufficient. You need to parse it in a reliable way according to the file type.

**Comment by bcullman** [comment]
For me to *consume* your CSS/LESS/SASS var values in my local CSS/LESS/SASS, I need to be able to easily read them. 

When I am ready to publish what ever component or app I have, I will be webpacking/minifying/treeshaking, etc that code. There is no need for you to deliver them minified

Delivering them minified like this also has the added detriment of making it almost impossible to track changes over time, as the diffs will almost always occur the the same line number.

**Comment by andreas-roessler** [comment]
The “less” files over the theme hierarchy are the source for the CSS/LESS/SASS build output files. You can track those non-minified files for changes.

The repo files are intended to be used directly … not as a parsed source for another build input (not sure why you need to parse it). Therefore, a minified output makes sense from my point of view. 
Anyway, I see the still the point of the readability of the variable files for humans. Especially in the current introduction phase of the parameters. So I agree that the minification should be disabled for those variable files. I discuss it in the team and ask for an item in our backlog.
The problem is that the files in the repo are a part of the SAP Base content build which is completely minified. Unfortunately, the minification is done while the file creation and is not a post build step. It can only be turned on/off for all files ... for all official deliveries.
We need some code which excludes the variable files from minification.
